---
name: cmpsc-100-fall-2018-practical3
break: true
indent: 4
---
src/main:
    java:
        practicalthree/ComputeMoonDistance.java:
            --single 2 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 4
            --fragment "new Date(" --count 1
--commits 4
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 4 --exact
